### ISSUE TITLE
GetIngredients doesn't respect NBT tags

### ISSUE THREAD

**Issue by knexer** [McJty/RFToolsControl#93]
Minimal demo program: https://pastebin.com/3VCcw5yn
Place a workbench with a recipe for electronic circuits below the processor, and a chest above.
Put non-insulated copper cable in the chest.
Expected: Processor does not take the copper cable, since it is not a component of the circuit's recipe.
Actual: Processor does take the copper cable, arranging it in its inventory as if it were insulated copper cable.

These items differ in the value of one of their NBT tags (as well as "Meta's Unlocalized Name") as per their advanced tooltips.

Other items that are only differentiated by NBT data - forestry capsules, enderio soul vials, and vanilla potions, for example - are presumably affected by this issue as well.

**Comment by tofof** [comment]
Yeah, IC2 really bites hard here with the insulated/uninsulated cables being NBT data and quite distinct for recipes. RFToolsControl would be the savior in the Age of Engineering modpack to deal with the grind, but it can't handle these.

**Comment by tofof** [comment]
Oh, in case it's relevant:
rftoolsctrl-1.1x-1.6.8 in MC 1.10.2

**Comment by McJty** [comment]
I don't know how to fix this in a good way. The problem is that for many recipes NBT does not matter. i.e. it is perfectly valid to upgrade an RFTools crafter to next tier regardless of the NBT in the crafter (i.e. current stored info). So ... this may be unsolvable unless someone has a suggestion?

**Comment by tofof** [comment]
Well, how about a couple nbt-sensitive GetIngredients and GetIngredientsSmart opcodes?  Actually, even better, just an optional parameter to those opcodes that can make them NBT sensitive (and default to false, i.e. the current behavior).

Then, it shouldn't be too bad to check areItemStackTagsEqual in addition to areItemsEqual when that parameter is true...

For the player, if they need to have both nbt-sensitive crafting and nbt-blind crafting, my understanding is that they can do seperate programs, one using it with that parameter and the other without, that look at different crafting card inventories to get the desired behavior on a per-recipe basis.

**Comment by McJty** [comment]
I think I have another solution that you can handle with a single get_ingredients. The fact that a recipe can work with items of different NBT is a property of the recipe itself. I think I'll add an extra option to crafting cards so that you can specify this with the recipe and let get_ingredients check that option

**Comment by McJty** [comment]
Ok, in next version (1.7.0) crafting cards will have an extra feature to allow 'strict nbt' matching for getting ingredients. This should fix this issue. get_ingredients and get_ingredients_smart will honor that flag

**Comment by tofof** [comment]
Brilliant! That does seem like a superior way to handle things.

I imagine you already realize this, but that would also be the ideal way to
add OreDictionary support.

Finally, fyi, in a couple places you do string matching on resultnbt and
serializenbt - I think from the same PR that had logic issues in issue #94.
You probably want to replace these with ItemStack.areItemStackTagsEqual()
instead.

**Comment by tofof** [comment]
I tested your changes and they didn't work for me.

I had an item with NBT data on it, used in a crafting card that I marked strict-NBT. When the processor did a getIngredientsSmart it only pulled the normal items - it didn't move the nbt-containing item into its internal inventory. Furthermore, getIngredientsSmart returned 0 indicating success.

I've created a PR (#116) that fixed this issue by using ItemStack.areItemStackTagsEqual(....) instead of the string comparison. The change to isEqualAdvanced(...) was enough to fix the issue for me, but in the PR I change the string comparisons in both InventoryTools and ProcessorTileEntry because I suspect bad behavior in both places. I didn't touch the one in CraftingStationTileEntry because it would be a more complicated refactoring.

**Comment by tofof** [comment]
On further review this doesn't quite fix it; the processor will fail to request missing nbt-specific items while using getIngredientsSmart, and again is returning 0 as if everything had succeeded.

**Comment by McJty** [comment]
Hmm. strange. From the logic it should work. What's the easiest way to test this? What kind of items are there that are distinct based on NBT that are easy to put in my dev env?

**Comment by tofof** [comment]
For NBT data, the easiest thing is to enchant some swords. [Patterened](https://minecraft.gamepedia.com/Banner#Stripes) banners  also work.

Program: https://gist.github.com/tofof/b0b87024b5857a1adeef1665661adef6
Crafting card:
```
 L     L 
    S       --->   Enchantment Table
 L     L              Strict NBT
```
Lapis in the corners, **sword with knockback 1** in the center, claims to create an enchantment table. 
**Uses strict NBT matching.**

----

My testing results (from hitting the button while the north inventory has various contents):

**Inventory**: Lapis + wrong swords (unnchanted or wrong enchantments)
**Result**: processor pulls the lapis only, getIngredientsSmart returns 0.
**Expected**: processor doesn't pull anything, getIngredientsSmart returns -1 (or throws a Missing Crafting Station exception)

**Inventory**: Lapis + correct sword + incorrect swords
**Result**: processor pulls the lapis and correct sword, getIngredientsSmart returns 0
**OK**

**Inventory**: Correct sword, but only 0-3 lapis
**Result**: processor pulls nothing, getIngredientsSmart returns -1 (or throws a Missing Crafting Station exception)
**OK**

_With a [program](https://gist.github.com/tofof/d866ca2518a3a61b7078937e93cd7654) that handles crafting stations_
_and an extra crafting card that claims to create the correct sword_
**Inventory** Lapis, no swords
**Result** processor pulls the lapis, getIngredientsSmart returns 0.
**Expected**: a crafting request for the correct sword is created at the crafting station, getIngredientsSmart returns 1
